AllCops:
  TargetRubyVersion: 2.6
Documentation:
  Enabled: false
Layout/LineLength:
  Max: 120
Metrics/BlockLength:
  Max: 120
Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"
Style/FrozenStringLiteralComment:
  Enabled: false
