version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5
    steps:
      - checkout
  test:
    docker:
      - image: circleci/ruby:2.6.5
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rspec

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test
